### ISSUE TITLE
Do backbone in VSGNet use imagenet-pretrained parameters?

### ISSUE THREAD

**Issue by xxxzhi** [ASMIftekhar/VSGNet#10]
Hi, do the resnet152 backbone in VSGNet use imagenet-pretrained parameters?

Here:

model = models.resnet152(pretrained=True)

from torchvision. 

btw, the object detector of all models in table 5 in your paper is same?

**Comment by ASMIftekhar** [comment]
Yes, the backbone is pretrained and frozen.

Object detector is same for all models. Our object detection results are public.

**Comment by xxxzhi** [comment]
Thanks for your reply. 

Do you ever try to use COCO-pretrained faster-rcnn backbone? It should achieve better performance?

**Comment by ASMIftekhar** [comment]
If I understand correctly, you want to use a backbone fine tuned in coco dataset. I didn’t try that. It might help numerically to improve the score.

**Comment by xxxzhi** [comment]
Thanks for your reply. I'm just curious if you tried that.
