### ISSUE TITLE
hi, how to train the feature extraction network(renset152) ?

### ISSUE THREAD

**Issue by bitwangdan** [ASMIftekhar/VSGNet#11]
I want to experiment on my own dataset, How do I train the feature extraction network?

**Comment by ASMIftekhar** [comment]
In scripts/model.py [line 35](https://github.com/ASMIftekhar/VSGNet/blob/0979447b1f40049442f5f173eb0479de93c3cfe9/scripts/model.py#L35l) declare the pretained model, you can just keep it in the trainable parameter list. 

One easy way to do that is to change the condition in scripts/main.py [line 113](https://github.com/ASMIftekhar/VSGNet/blob/0979447b1f40049442f5f173eb0479de93c3cfe9/scripts/main.py#L113l). As you can see we are keeping the pretrained model in not_trainbles list,  you can just change the condition.

Hope this helps, thank you.

**Comment by bitwangdan** [comment]
@ASMIftekhar Thank you for your reply. How do I pre-train resnet152 on my own dataset?  Then I fixed the model and trained the HOI model

**Comment by ASMIftekhar** [comment]
In that case, you can generate object detection results and annotations results like our generated results for V-COCO (Please check the downloaded data)and just change the files which are being loaded in scripts/helpers_preprocess.py.

**Comment by Radleye** [comment]
> I want to experiment on my own dataset, How do I train the feature extraction network?

hello.Do you know how to make own dataset(HOI) , i confused aboout that
