### ISSUE TITLE
The question about training HICO-DET

### ISSUE THREAD

**Issue by XILIANGL** [ASMIftekhar/VSGNet#12]
When I train on the HICO-DET dataset, there is a problem "IOError: No such file or directory: u' ../All_data/Object_Detections_hico/train/HICO_train2015_00031770.json" . And, I notice that there is no file in the above path. So where can I find the correct file?

**Comment by ASMIftekhar** [comment]
Hello, I just redownloaded the data and manually check. The file was there. So either your download is incomplete or you are not in the correct directory while running the command. Please check the readme for details. If you wanna manually download the data, please use this [link](https://drive.google.com/drive/u/1/folders/1J8mN63bNIrTdBQzq7Lpjp4qxMXgYI-yF) and download "All_data.zip".
