### ISSUE TITLE
Hi, in pool_pairing.py, What is the role of sp_features?

### ISSUE THREAD

**Issue by bitwangdan** [ASMIftekhar/VSGNet#13]
![image](https://user-images.githubusercontent.com/18326564/100316322-3c4b6880-2ff5-11eb-9d50-17b16153bc56.png)

**Comment by ASMIftekhar** [comment]
Hello,
Thanks for your interest in our work. sp_features is the encoding of the human bounding box relative to the object bounding box. Please refer to equation 3 from this [paper](URL) for more details. We concatenate these sp features for each human-object pair with the extracted features of humans and objects.
