### ISSUE TITLE
the graph structure

### ISSUE THREAD

**Issue by ht014** [ASMIftekhar/VSGNet#15]
Hi,  thanks for your impressive project. Here I have a question about the  graph structure, as showing below:
https://github.com/ASMIftekhar/VSGNet/blob/0979447b1f40049442f5f173eb0479de93c3cfe9/scripts/model.py#L251
For the people node, you select all the people but for object nodes,
https://github.com/ASMIftekhar/VSGNet/blob/0979447b1f40049442f5f173eb0479de93c3cfe9/scripts/model.py#L253
 I am confused why you skip the first object, that is, objects_this_batch=objects_only[start_o:start_o+int(l[1])][**_1:_**].

**Comment by ASMIftekhar** [comment]
Hello,
Thanks for your interest in our work. For V-COCO dataset, the first object actually refers to the no-object case. So there is no point in including it in the graph network. A more detailed discussion can be found here: Issue #6
