### ISSUE TITLE
Performance on V-COCO

### ISSUE THREAD

**Issue by nkliuyifang** [ASMIftekhar/VSGNet#2]
Dear Sir, 

Thanks for your excellent work!
VSGNet is expected to achieve 51.76mAP (Sc 1).
While, I got 49.70 using your provided pretrained model.
![1](https://user-images.githubusercontent.com/41351688/81402793-a5a48080-9164-11ea-81a0-46ceeec2131d.png)

**Comment by ASMIftekhar** [comment]
As mentioned in the paper, following previous works, we did not consider the class point as  it has insufficient numbers of samples to work on. So your refined mAP would be:(49.7*25-0.34)/24=51.76. Thanks
