### ISSUE TITLE
hi, Which test script can obtain this metric?

### ISSUE THREAD

**Issue by bitwangdan** [ASMIftekhar/VSGNet#21]
![image](https://user-images.githubusercontent.com/18326564/126421048-f84089b2-eccb-44ae-a079-c5c2f4817db9.png)

**Comment by ASMIftekhar** [comment]
Plese see: [evaluation in v-coco](https://github.com/ASMIftekhar/VSGNet#evaluation-in-v-coco). Also, have a look on this [issue](https://github.com/ASMIftekhar/VSGNet/issues/2).
