### ISSUE TITLE
How to get the infos/prior.pickle ?

### ISSUE THREAD

**Issue by ChinaYi** [ASMIftekhar/VSGNet#24]
This file seems to be used to determine the types of interactions that objects may participate in， but I do not know how to generate it. I try to traverse all the training and test data and record the interaction categories that the object may participate in，but I get totally different results compared to the prior.pickle.

**Comment by ASMIftekhar** [comment]
prior.pickle is just a pickled version of this [script](https://github.com/vt-vl-lab/iCAN/blob/master/lib/ult/apply_prior.py). This is a hand made prior suggested by iCAN. Therefore, it is not perfect. However, unlike HICO-DET there are unknown action-object combinations (~7% of total action-object combinations)  in V-COCO test set. That is why I decided to use this prior. I guess using a better prior will generate a better performance.  But for creating a perfect prior, we need to utilize both training and testing data, I am not sure if that is the correct thing to do.

**Comment by ChinaYi** [comment]
Thks
