### ISSUE TITLE
 When running train, it stays in this state for a long time and does not run

### ISSUE THREAD

**Issue by mansooreh1** [ASMIftekhar/VSGNet#25]
I want to run the program, but when I run "CUDA_VISIBLE_DEVICES=0 python main.py -fw new_test -ba 8 -l 0.001 -e 80 -sa 20", but it stays in this state for a long time and does not run. Why?That is, there is no progress. Is this correct? Or is wrong?
![image](https://user-images.githubusercontent.com/40629504/163851005-3997b752-d446-4f5b-9564-465d08e1c0bc.png)

**Comment by ASMIftekhar** [comment]
Without looking into your system, I can't answer your question. However, did you download the dataset fully? If this is HICO-DET's training set, the number of iteration should be more than 73.

**Comment by mansooreh1** [comment]
I think loop for  have a problem. I think it gets stuck in an infinite loop. Because the code and the loops and the spaces and tabs related to the loops and functions are flawed.

**Comment by ASMIftekhar** [comment]
Can you have a look on this issue https://github.com/ASMIftekhar/VSGNet/issues/9 ?

**Comment by mansooreh1** [comment]
Excuse me, I did that too, but my problem was not solved. I feel stuck in an infinite loop.

**Comment by ASMIftekhar** [comment]
Ok. The next thing we can do is to find out which line it is getting stuck. You can put break point at the beginning of the loop and then execute one by one line. My best guesses are either it is getting stuck while sending the model to the gpu or calling the data loader.

**Comment by mansooreh1** [comment]
Thanks for your attention. Based on your tips, I think part "dataloader" has a problem. When I  type print(enumerate(tqdm(dataloader[phase]))) in line 219 of train_test.py, the output is "<enumerate object at 0x7fa0b9b75948>". This means that there is no i and iterr in line of code "for iterr,i in enumerate(tqdm(dataloader[phase])):"

**Comment by mansooreh1** [comment]
Hello. I checked the entire of code. The main problem is with line 219 of code train_test.py in folder scripts_hico. "enumerate(tqdm(dataloader[phase]))" has not no values such as i and iterr. It has a problem and it does not have i and iterr value. please help me

**Comment by ASMIftekhar** [comment]
print(enumerate(tqdm(dataloader[phase]))) ---the output is "<enumerate object at 0x7fa0b9b75948>" this is expected, as you are wrapping the dataloader with enumerate function, it becomes an enumerate object.  

Please print(iterr, i) to check if dataloader is working or not. I would strongly suggest to put a breakpoint instead of using print functions to debug.

Reference:
https://www.geeksforgeeks.org/enumerate-in-python/
