### ISSUE TITLE
hi，Can this model be converted to TRT?

### ISSUE THREAD

**Issue by bitwangdan** [ASMIftekhar/VSGNet#3]

**Comment by ASMIftekhar** [comment]
Hello, I am sorry but what is TRT?

**Comment by amilworks** [comment]
I believe he is asking if you can convert your awesome model to **TensorRT**, mostly used for inference.

**Comment by ASMIftekhar** [comment]
Thanks @amilworks for clarifying that. Right now we do not have any interest to do that, but if anyone else is interested then we can certainly help.
