### ISSUE TITLE
Which Faster R-CNN model is adopted to generate the object detetction results? 

### ISSUE THREAD

**Issue by MuchHair** [ASMIftekhar/VSGNet#5]
Is the Faster R-CNN model also based on the ResNet-152 backbone that is used for feature exrtraction ？Thanks for reply.

**Comment by oulutan** [comment]
The object detector is separate and uses its own backbone. We used the [tf object detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) with the architecture `faster_rcnn_nas_coco_2018_01_28`. We also provide the object detection results that we generated. If you use the `bash download_data.sh`, it will download the object detection results as well
