### ISSUE TITLE
Could you help to format the code for hico?

### ISSUE THREAD

**Issue by xxxzhi** [ASMIftekhar/VSGNet#9]
Hi, thanks for your work. But I find the code is unformatted and in some place, I can not figure how to format the code. Could you format it?

unformatted code like this:

https://github.com/ASMIftekhar/VSGNet/blob/0979447b1f40049442f5f173eb0479de93c3cfe9/scripts_hico/model.py#L180

**Comment by ASMIftekhar** [comment]
Hello,
Thanks for your interest in our work.

Unfortunately, without knowing anything about your environment I can't give you any suggestion on "formatting" the code. The code seems to work fine on different systems used by me. The quick blind suggestion I can give is to open the code in vim and use :retab command.

**Comment by xxxzhi** [comment]
Hi, 
Thanks for your reply,

Do you use vim to edit the code? When I use pycharm, there are various kinds of errors.

**Comment by xxxzhi** [comment]
Thanks, I have solved my problem according to your suggestion.
